"""Agent Query Engine - Stateful deep queries over the wiki knowledge base.

Unlike RAG which is stateless, this engine:
1. Reads index.md to navigate to relevant topics
2. Traverses bilateral links to gather context
3. Maintains state across queries
4. Saves high-quality Q&A back to the wiki
"""

import logging
from pathlib import Path
from typing import Optional
from datetime import datetime

from ..utils.model_router import get_router
from .context_manager import ContextManager

logger = logging.getLogger(__name__)


class AgentQuery:
    """Perform stateful queries over the wiki knowledge base."""

    def __init__(
        self,
        wiki_dir: Path,
        outputs_dir: Optional[Path] = None,
        model: Optional[str] = None,
        token_budget: int = 100000,
    ):
        self.wiki_dir = wiki_dir
        self.outputs_dir = outputs_dir or (wiki_dir.parent / "outputs" / "qa")
        self.model = model or "qwen3.6-plus"
        self.router = get_router()

        # Context management
        self.context_manager = ContextManager(
            wiki_dir=wiki_dir,
            token_budget=token_budget,
        )

        # Ensure output directory exists
        self.outputs_dir.mkdir(parents=True, exist_ok=True)

    def query(self, question: str, save_result: bool = True) -> str:
        """Perform a deep query over the wiki.

        Args:
            question: The question to answer
            save_result: Whether to save the Q&A to outputs/

        Returns:
            Answer generated by the agent
        """
        logger.info(f"Query: {question}")

        # Step 1: Find existing similar Q&A (knowledge reuse)
        existing_qa = self._find_similar_qa(question)

        # Step 2: Load relevant context from index
        context = self.context_manager.load_for_query(question)

        # Add Q&A history to context
        if existing_qa:
            context['qa_history'] = self._format_qa_history(existing_qa)
        else:
            context['qa_history'] = '暂无相关 Q&A 记录'

        # Step 3: Generate answer using LLM
        answer = self._generate_answer(question, context)

        # Step 4: Save high-quality Q&A
        if save_result and self._is_worth_saving(question, answer):
            self._save_qa(question, answer, context)

        return answer

    def _generate_answer(self, question: str, context: dict) -> str:
        """Generate answer using LLM with wiki context.

        Args:
            question: User's question
            context: Dictionary with loaded wiki content

        Returns:
            Generated answer with source attribution
        """
        # Build prompt with context - Agentic Wiki style (LLM learns then answers)
        context_text = self._format_context(context)

        prompt = f"""你是一个知识助手。请先阅读以下 wiki 知识网络，然后回答问题。

## 你已学习的知识（来自 wiki）

{context_text}

## 用户问题

{question}

## 回答指南

1. **优先使用 wiki 知识**: 如果 wiki 中有相关内容，用它作为回答的核心
2. **补充通用知识**: 如果 wiki 内容不足，用你的通用知识补充，但要标注
3. **引用来源**: 提到 wiki 中的概念时，用 [[概念名]] 格式引用
4. **标注知识边界**: 明确说明哪些来自 wiki，哪些是你的补充

## 回答格式

### 来自知识库的内容
[基于 wiki 的回答，带 [[链接]]]

### 补充说明（如有）
[如果 wiki 内容不足，这里用通用知识补充，标注"知识库尚未收录"]

如果 wiki 中有相关 Q&A 记录，也请参考：
{context.get('qa_history', '暂无相关 Q&A 记录')}
"""

        try:
            response = self.router.call(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=2000,
                temperature=0.5,
            )
            return response.strip()
        except Exception as e:
            logger.error(f"Failed to generate answer: {e}")
            return f"抱歉，生成答案时遇到错误：{e}"

    def _format_context(self, context: dict) -> str:
        """Format loaded context for the prompt.

        Args:
            context: Dictionary with index, entries, related

        Returns:
            Formatted context string
        """
        lines = []

        # Add index excerpt
        if context.get("index"):
            lines.append("### 知识库索引（相关部分）\n")
            lines.append(context["index"][:2000])  # Truncate index
            lines.append("")

        # Add wiki entries
        if context.get("entries"):
            lines.append("### 相关词条\n")
            for name, content in context["entries"].items():
                # Extract first 500 chars of each entry
                preview = content[:500] + "..." if len(content) > 500 else content
                lines.append(f"#### [[{name}]]\n{preview}\n")

        # Add related concepts
        if context.get("related"):
            lines.append("### 相关概念\n")
            lines.append(", ".join(f"[[{r}]]" for r in context["related"]))

        return "\n".join(lines) if lines else "暂无相关上下文"

    def _is_worth_saving(self, question: str, answer: str) -> bool:
        """Determine if a Q&A is worth saving.

        Criteria:
        - Answer is substantial (>200 chars)
        - No error messages
        - Contains useful information
        """
        if len(answer) < 200:
            return False
        if "错误" in answer or "抱歉" in answer:
            return False
        return True

    def _save_qa(self, question: str, answer: str, context: dict) -> Path:
        """Save Q&A to outputs/qa/.

        Args:
            question: Original question
            answer: Generated answer
            context: Context used

        Returns:
            Path to saved Q&A file
        """
        # Generate filename from question
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_question = self._slugify(question)[:40]
        filename = f"{timestamp}_{safe_question}.md"
        output_path = self.outputs_dir / filename

        # Extract related concepts from context
        related = list(context.get("entries", {}).keys())

        # Build Q&A content
        content = f"""---
type: qa
question: {question}
answered_at: {datetime.now().isoformat()}
related_topics: {related}
model: {self.model}
---

# 问题

{question}

# 回答

{answer}

---

*此 Q&A 由 Agentic Wiki 系统自动生成并保存。*
"""

        output_path.write_text(content, encoding="utf-8")
        logger.info(f"Saved Q&A to {output_path}")

        return output_path

    def _slugify(self, text: str) -> str:
        """Convert text to a safe filename slug."""
        slug = text.replace(" ", "_").replace("/", "_")
        slug = "".join(c for c in slug if c.isalnum() or c in "_-")
        return slug

    def query_with_followup(
        self,
        initial_question: str,
        followup_questions: list[str],
    ) -> list[str]:
        """Perform an initial query followed by related queries.

        This builds a "Q&A tree" for complex topics.

        Args:
            initial_question: First question
            followup_questions: List of follow-up questions

        Returns:
            List of answers
        """
        answers = []

        # Initial query
        logger.info(f"Starting Q&A session with: {initial_question}")
        answers.append(self.query(initial_question, save_result=False))

        # Follow-up queries
        for q in followup_questions:
            logger.info(f"Follow-up: {q}")
            answers.append(self.query(q, save_result=False))

        # Save the entire session
        session_path = self._save_qa_session(
            initial_question,
            list(zip([initial_question] + followup_questions, answers)),
        )

        logger.info(f"Saved Q&A session to {session_path}")
        return answers

    def _save_qa_session(
        self,
        topic: str,
        qa_pairs: list[tuple[str, str]],
    ) -> Path:
        """Save a complete Q&A session.

        Args:
            topic: Session topic
            qa_pairs: List of (question, answer) pairs

        Returns:
            Path to saved session file
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = self._slugify(topic)[:40]
        filename = f"{timestamp}_session_{safe_topic}.md"
        output_path = self.outputs_dir / filename

        content = f"""---
type: qa_session
topic: {topic}
created_at: {datetime.now().isoformat()}
num_questions: {len(qa_pairs)}
---

# Q&A 会话：{topic}

"""
        for i, (question, answer) in enumerate(qa_pairs, 1):
            content += f"""
## 问题 {i}

{question}

### 回答

{answer}

---
"""

        output_path.write_text(content, encoding="utf-8")
        return output_path

    def _find_similar_qa(self, question: str, limit: int = 3) -> list[dict]:
        """Find similar Q&A records using keyword matching.

        Args:
            question: The user's question
            limit: Maximum number of Q&A to return

        Returns:
            List of Q&A dictionaries with question, answer, and metadata
        """
        if not self.outputs_dir.exists():
            return []

        # Extract keywords from question
        keywords = self._extract_keywords(question)

        # Search Q&A files
        qa_records = []
        for qa_file in self.outputs_dir.glob("*.md"):
            try:
                content = qa_file.read_text(encoding="utf-8")

                # Check if any keyword matches
                score = sum(1 for kw in keywords if kw.lower() in content.lower())

                if score > 0:
                    metadata = self._parse_qa_frontmatter(content)
                    qa_records.append({
                        "path": qa_file,
                        "question": metadata.get("question", ""),
                        "answer": content.split("---\n", 3)[-1] if "---\n" in content else "",
                        "score": score,
                        "answered_at": metadata.get("answered_at", ""),
                    })
            except Exception as e:
                logger.warning(f"Failed to parse Q&A file {qa_file}: {e}")

        # Sort by relevance score and return top matches
        qa_records.sort(key=lambda x: x["score"], reverse=True)
        return qa_records[:limit]

    def _format_qa_history(self, qa_records: list[dict]) -> str:
        """Format Q&A history for inclusion in prompt.

        Args:
            qa_records: List of Q&A dictionaries

        Returns:
            Formatted Q&A history string
        """
        if not qa_records:
            return "暂无相关 Q&A 记录"

        lines = ["已有的相关问答：\n"]
        for i, qa in enumerate(qa_records, 1):
            lines.append(f"**Q{i}: {qa['question']}**")
            lines.append(f"A: {qa['answer'][:300]}...\n" if len(qa['answer']) > 300 else f"A: {qa['answer']}\n")
            lines.append("")

        return "\n".join(lines)

    def _extract_keywords(self, text: str) -> list[str]:
        """Extract keywords from text for similarity matching.

        Args:
            text: Input text

        Returns:
            List of keywords (Chinese words and English terms)
        """
        import re

        # Simple keyword extraction:
        # - Chinese: 2-4 character sequences
        # - English: whole words

        keywords = []

        # Extract Chinese phrases (2-4 chars)
        chinese_pattern = re.compile(r'[\u4e00-\u9fff]{2,4}')
        keywords.extend(chinese_pattern.findall(text))

        # Extract English words (4+ chars for meaningful terms)
        english_pattern = re.compile(r'\b[a-zA-Z]{4,}\b')
        keywords.extend(english_pattern.findall(text))

        # Remove duplicates while preserving order
        seen = set()
        unique_keywords = []
        for kw in keywords:
            if kw.lower() not in seen:
                seen.add(kw.lower())
                unique_keywords.append(kw)

        return unique_keywords

    def _parse_qa_frontmatter(self, content: str) -> dict:
        """Parse YAML frontmatter from Q&A file.

        Args:
            content: Q&A file content

        Returns:
            Dictionary with metadata
        """
        metadata = {}

        if not content.startswith("---"):
            return metadata

        parts = content.split("---", 3)
        if len(parts) < 3:
            return metadata

        for line in parts[1].strip().split("\n"):
            if ":" in line:
                key, value = line.split(":", 1)
                metadata[key.strip()] = value.strip()

        return metadata
